import { useEffect, useState } from "react";
import { Copy, Plus } from "@phosphor-icons/react";
import { Button } from "@/components/ui/button";
import { ConfirmationDialog } from "@/components/ConfirmationDialog";
import { createPersonalApiToken, listPersonalApiTokens, revokePersonalApiToken, type PersonalApiToken } from "@/account/personalApiTokenApi";

export function PersonalApiTokensPanel() {
  const [items, setItems] = useState<PersonalApiToken[]>([]); const [name, setName] = useState(""); const [creating, setCreating] = useState(false); const [createdValue, setCreatedValue] = useState<string | null>(null); const [pending, setPending] = useState<PersonalApiToken | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void listPersonalApiTokens().then(setItems).catch(() => setError("Não foi possível carregar tokens de API.")); }, []);
  async function create() { if (!name.trim()) return; setCreating(true); setError(null); try { const result = await createPersonalApiToken(name.trim()); setItems((current) => [result.token, ...current]); setName(""); setCreatedValue(result.value); } catch { setError("Não foi possível criar o token."); } finally { setCreating(false); } }
  async function revoke() { if (!pending) return; try { await revokePersonalApiToken(pending.id); setItems((current) => current.map((item) => item.id === pending.id ? { ...item, revokedAt: new Date().toISOString() } : item)); } catch { setError("Não foi possível revogar o token."); } finally { setPending(null); } }
  return <section className="grid gap-4 border-t border-border/75 pt-6"><header><p className="text-xs font-medium uppercase tracking-[.12em] text-primary">Integrações</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-foreground">Tokens de API</h2><p className="mt-1 text-sm text-muted-foreground">Use tokens de API para conectar ferramentas como o MCP do No8do.</p></header><div className="flex flex-wrap gap-2"><input className="h-9 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm" value={name} onChange={(e) => setName(e.target.value)} maxLength={160} placeholder="Nome do token, por exemplo Codex local" /><Button type="button" size="sm" onClick={() => void create()} disabled={creating || !name.trim()}><Plus className="h-4 w-4" />{creating ? "Criando..." : "Criar token"}</Button></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}{items.length === 0 ? <p className="border-y border-border py-4 text-sm text-muted-foreground">Nenhum token de API criado.</p> : <div className="divide-y divide-border border-y border-border">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">Criado em {new Date(item.createdAt).toLocaleDateString("pt-BR")} · {item.revokedAt ? "Revogado" : "Ativo"}</p></div>{!item.revokedAt ? <Button size="sm" variant="ghost" className="text-destructive" onClick={() => setPending(item)}>Revogar</Button> : null}</div>)}</div>}{createdValue ? <div className="fixed inset-0 z-[80] grid place-items-center bg-foreground/20 p-4"><section className="w-full max-w-lg rounded-lg border border-border bg-card p-5 shadow-xl" role="dialog" aria-modal="true"><h3 className="text-lg font-semibold">Token criado</h3><p className="mt-1 text-sm text-muted-foreground">Copie agora. Este token não será exibido novamente.</p><code className="mt-4 block break-all rounded-md border border-border bg-muted p-3 text-sm">{createdValue}</code><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setCreatedValue(null)}>Fechar</Button><Button onClick={() => void navigator.clipboard.writeText(createdValue)}><Copy className="h-4 w-4" />Copiar token</Button></div></section></div> : null}<ConfirmationDialog open={Boolean(pending)} title="Revogar token?" message="Ferramentas que usam este token perderão acesso." itemName={pending?.name} confirmLabel="Revogar" loadingLabel="Revogando..." destructive onCancel={() => setPending(null)} onConfirm={() => void revoke()} /></section>;
}
