package com.no8do.api.agent;

public enum AgentRegistryAuditEventType {
    AGENT_CREATED,
    AGENT_UPDATED,
    AGENT_LIFECYCLE_CHANGED,
    AGENT_CREDENTIAL_CREATED,
    AGENT_CREDENTIAL_REVOKED,
    AGENT_CREDENTIAL_ROTATED,
    AGENT_PROJECT_ASSIGNED,
    AGENT_PROJECT_UNASSIGNED,
    AGENT_CONNECTION_ASSIGNED,
    AGENT_CONNECTION_UNASSIGNED,
    AGENT_CAPABILITY_GRANTED,
    AGENT_CAPABILITY_REVOKED,
    AGENT_WORK_ITEM_ASSIGNED,
    AGENT_WORK_ITEM_UNASSIGNED
}
