import { type FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Copy, GearSix, GithubLogo, Plus, Trash, UsersThree } from "@phosphor-icons/react";
import { useAuth } from "@/auth/AuthContext";
import { Button } from "@/components/ui/button";
import { createWorkspaceInvite, deleteWorkspace, disconnectWorkspaceGithubAppInstallation, getWorkspaceGithubAppInstallation, getWorkspaceGithubAppInstallUrl, listWorkspaceInvites, listWorkspaceMembers, removeWorkspaceMember, revokeWorkspaceInvite, updateWorkspaceMember, type Workspace, type WorkspaceGithubAppInstallation, type WorkspaceInvite, type WorkspaceInviteRole, type WorkspaceMemberManagement, type WorkspaceRole } from "@/workspaces/workspaceApi";

const roleLabel: Record<WorkspaceRole, string> = { OWNER: "Owner", ADMIN: "Administrador", MEMBER: "Membro", VIEWER: "Visualizador" };
const editableRoles: Exclude<WorkspaceRole, "OWNER">[] = ["ADMIN", "MEMBER", "VIEWER"];
const pending = (invite: WorkspaceInvite) => !invite.acceptedAt && !invite.revokedAt && new Date(invite.expiresAt) > new Date();

export function WorkspaceSettingsPage({ workspace, onReturnToWorkspace, onWorkspaceDeleted }: { workspace: Workspace; onReturnToWorkspace: () => void; onWorkspaceDeleted: (workspaceId: string) => void }) {
  const { user } = useAuth();
  const [members, setMembers] = useState<WorkspaceMemberManagement[]>([]); const [membersLoading, setMembersLoading] = useState(true); const [membersError, setMembersError] = useState<string | null>(null); const [updatingMemberId, setUpdatingMemberId] = useState<string | null>(null); const [removingMember, setRemovingMember] = useState<WorkspaceMemberManagement | null>(null);
  const [invites, setInvites] = useState<WorkspaceInvite[]>([]); const [invitesLoading, setInvitesLoading] = useState(true); const [invitesError, setInvitesError] = useState<string | null>(null); const [inviteEmail, setInviteEmail] = useState(""); const [inviteRole, setInviteRole] = useState<WorkspaceInviteRole>("VIEWER"); const [savingInvite, setSavingInvite] = useState(false); const [inviteUrl, setInviteUrl] = useState<string | null>(null);
  const [github, setGithub] = useState<WorkspaceGithubAppInstallation | null>(null); const [githubError, setGithubError] = useState<string | null>(null); const [installing, setInstalling] = useState(false); const [disconnectGithubOpen, setDisconnectGithubOpen] = useState(false); const [disconnectingGithub, setDisconnectingGithub] = useState(false);
  const [confirmName, setConfirmName] = useState(""); const [deleting, setDeleting] = useState(false); const [deleteError, setDeleteError] = useState<string | null>(null); const [deleteOpen, setDeleteOpen] = useState(false);
  useEffect(() => { let active = true; setMembersLoading(true); setMembersError(null); void listWorkspaceMembers(workspace.id).then(v => { if (active) setMembers(v); }).catch(e => { if (active) setMembersError(e instanceof Error ? e.message : "Não foi possível carregar os membros."); }).finally(() => { if (active) setMembersLoading(false); }); return () => { active = false; }; }, [workspace.id]);
  useEffect(() => { let active = true; setInvitesLoading(true); setInvitesError(null); void listWorkspaceInvites(workspace.id).then(v => { if (active) setInvites(v.filter(pending)); }).catch(e => { if (active) setInvitesError(e instanceof Error ? e.message : "Não foi possível carregar os convites."); }).finally(() => { if (active) setInvitesLoading(false); }); return () => { active = false; }; }, [workspace.id]);
  useEffect(() => { let active = true; void getWorkspaceGithubAppInstallation(workspace.id).then(v => { if (active) setGithub(v); }).catch(e => { if (active) setGithubError(e instanceof Error ? e.message : "Não foi possível carregar a integração GitHub."); }); return () => { active = false; }; }, [workspace.id]);
  const canManage = (member: WorkspaceMemberManagement) => member.userId !== user?.id && (workspace.role === "OWNER" ? member.role !== "OWNER" : member.role === "MEMBER" || member.role === "VIEWER");
  const rolesFor = (_member?: WorkspaceMemberManagement) => workspace.role === "ADMIN" ? editableRoles.filter(role => role !== "ADMIN") : editableRoles;
  async function changeRole(member: WorkspaceMemberManagement, role: Exclude<WorkspaceRole, "OWNER">) { setUpdatingMemberId(member.userId); setMembersError(null); try { const updated = await updateWorkspaceMember(workspace.id, member.userId, role); setMembers(current => current.map(item => item.userId === updated.userId ? updated : item)); } catch (e) { setMembersError(e instanceof Error ? e.message : "Não foi possível atualizar o papel do membro."); } finally { setUpdatingMemberId(null); } }
  async function removeMember() { if (!removingMember) return; setUpdatingMemberId(removingMember.userId); setMembersError(null); try { await removeWorkspaceMember(workspace.id, removingMember.userId); setMembers(current => current.filter(item => item.userId !== removingMember.userId)); setRemovingMember(null); } catch (e) { setMembersError(e instanceof Error ? e.message : "Não foi possível remover o membro."); } finally { setUpdatingMemberId(null); } }
  async function createInvite(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSavingInvite(true); setInvitesError(null); try { const invite = await createWorkspaceInvite(workspace.id, { email: inviteEmail, role: inviteRole }); setInvites(current => [invite, ...current]); setInviteEmail(""); setInviteUrl(invite.inviteUrl); } catch (e) { setInvitesError(e instanceof Error ? e.message : "Não foi possível criar o convite."); } finally { setSavingInvite(false); } }
  async function revoke(id: string) { setInvitesError(null); try { await revokeWorkspaceInvite(workspace.id, id); setInvites(current => current.filter(invite => invite.id !== id)); } catch (e) { setInvitesError(e instanceof Error ? e.message : "Não foi possível revogar o convite."); } }
  async function removeWorkspace(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setDeleting(true); setDeleteError(null); try { await deleteWorkspace(workspace.id, confirmName); onWorkspaceDeleted(workspace.id); } catch (e) { setDeleteError(e instanceof Error ? e.message : "Não foi possível excluir o workspace."); } finally { setDeleting(false); } }
  async function disconnectGithub() { if (disconnectingGithub) return; setDisconnectingGithub(true); setGithubError(null); try { await disconnectWorkspaceGithubAppInstallation(workspace.id); setGithub({ installed: false, installationId: null, accountId: null, accountLogin: null, accountType: null, configuredAt: null }); setDisconnectGithubOpen(false); } catch (e) { setGithubError(e instanceof Error ? e.message : "Não foi possível desvincular o GitHub."); } finally { setDisconnectingGithub(false); } }
  return <section className="mx-auto w-full max-w-4xl">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-6">
      <div><span className="flex items-center gap-2 text-xs font-medium uppercase tracking-[.1em] text-muted-foreground"><GearSix className="h-4 w-4 text-primary" />Workspace</span><h1 className="mt-2 text-3xl font-semibold text-foreground">Configurações</h1><p className="mt-1 text-sm text-muted-foreground">Acesso, convites e integrações de {workspace.name}.</p></div>
      <Button variant="ghost" size="sm" onClick={onReturnToWorkspace}><ArrowLeft />Voltar ao workspace</Button>
    </header>
    <main className="mt-7 divide-y divide-border border-y border-border">
      <section className="flex flex-wrap items-center justify-between gap-3 py-5"><div><p className="text-xs font-medium uppercase tracking-[.1em] text-muted-foreground">Workspace</p><h2 className="mt-1 text-xl font-semibold">{workspace.name}</h2></div><span className="rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">{roleLabel[workspace.role]}</span></section>
      <section className="py-6"><SectionHeading icon={UsersThree} title="Membros" description="Pessoas com acesso a este workspace." />
        {membersLoading ? <p className="py-5 text-sm text-muted-foreground">Carregando membros...</p> : null}{membersError ? <p className="mt-4 text-sm text-destructive" role="alert">{membersError}</p> : null}
        {!membersLoading && !membersError ? <div className="mt-4 divide-y divide-border">{members.map(member => <div key={member.userId} className="grid gap-3 py-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><p className="font-medium">{member.name}</p><p className="break-all text-xs text-muted-foreground">{member.email}</p></div>{canManage(member) ? <div className="flex flex-wrap items-center gap-2"><select className="h-8 rounded-md border border-input bg-background px-2 text-xs" value={member.role} disabled={updatingMemberId === member.userId} onChange={e => void changeRole(member, e.target.value as Exclude<WorkspaceRole, "OWNER">)}>{rolesFor(member).map(role => <option key={role} value={role}>{roleLabel[role]}</option>)}</select><Button size="sm" variant="ghost" className="text-destructive" disabled={updatingMemberId === member.userId} onClick={() => setRemovingMember(member)}><Trash />Remover</Button></div> : <span className="w-fit rounded-full border border-border bg-muted px-2.5 py-0.5 text-xs text-muted-foreground">{roleLabel[member.role]}</span>}</div>)}</div> : null}
        {removingMember ? <InlineConfirm title={`Remover ${removingMember.name} do workspace?`} description="Essa pessoa perderá acesso a este workspace. O conteúdo criado por ela será preservado." confirmLabel="Remover membro" pending={updatingMemberId === removingMember.userId} onConfirm={() => void removeMember()} onCancel={() => setRemovingMember(null)} /> : null}
      </section>
      <section className="py-6"><SectionHeading title="Convites pendentes" description="Compartilhe acesso sem expor dados sensíveis." />
        <form className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_180px_auto] sm:items-end" onSubmit={createInvite}><label className="grid gap-1 text-sm">E-mail<input className="h-9 rounded-md border border-input bg-background px-3" value={inviteEmail} onChange={e => setInviteEmail(e.target.value)} type="email" required /></label><label className="grid gap-1 text-sm">Permissão<select className="h-9 rounded-md border border-input bg-background px-3" value={inviteRole} onChange={e => setInviteRole(e.target.value as WorkspaceInviteRole)}><option value="ADMIN">Administrador</option><option value="VIEWER">Somente leitura</option></select></label><Button size="sm" disabled={savingInvite}><Plus />{savingInvite ? "Criando..." : "Convidar"}</Button></form>
        {inviteUrl ? <Button variant="ghost" size="sm" className="mt-2" onClick={() => void navigator.clipboard.writeText(inviteUrl)}><Copy />Copiar link do convite</Button> : null}{invitesLoading ? <p className="py-5 text-sm text-muted-foreground">Carregando convites...</p> : null}{invitesError ? <p className="mt-3 text-sm text-destructive" role="alert">{invitesError}</p> : null}{!invitesLoading && !invitesError ? <div className="mt-4 divide-y divide-border">{invites.length ? invites.map(invite => <div key={invite.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="break-all text-sm font-medium">{invite.email}</p><p className="text-xs text-muted-foreground">{roleLabel[invite.role]} · expira em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(invite.expiresAt))}</p></div><Button size="sm" variant="ghost" className="text-destructive" onClick={() => void revoke(invite.id)}><Trash />Revogar</Button></div>) : <p className="py-3 text-sm text-muted-foreground">Nenhum convite pendente.</p>}</div> : null}
      </section>
      <section className="py-6"><SectionHeading icon={GithubLogo} title="GitHub App" description={github?.installed ? `${github.accountLogin} está conectada a este workspace.` : "GitHub não conectado a este workspace."} />
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-l-2 border-primary/50 bg-muted/35 px-4 py-3"><p className="max-w-xl text-sm text-muted-foreground">{github?.installed ? "A desconexão remove apenas o vínculo local. Projetos e dados do No8do permanecem preservados." : "Autorize uma conta pessoal ou organização para usar a integração neste workspace."}</p>{github && !github.installed ? <Button size="sm" disabled={installing} onClick={() => { setInstalling(true); window.location.assign(getWorkspaceGithubAppInstallUrl(workspace.id)); }}>Instalar GitHub App</Button> : github?.installed ? <Button size="sm" variant="destructive" disabled={disconnectingGithub} onClick={() => setDisconnectGithubOpen(true)}>Desvincular GitHub</Button> : null}</div>{githubError ? <p className="mt-3 text-sm text-destructive" role="alert">{githubError}</p> : null}
        {disconnectGithubOpen ? <InlineConfirm title="Desvincular o GitHub deste workspace?" description="A integração deixará de estar disponível para este workspace. Seus projetos e dados do No8do não serão excluídos. A instalação poderá continuar no GitHub até ser removida por lá." confirmLabel="Desvincular GitHub" pending={disconnectingGithub} onConfirm={() => void disconnectGithub()} onCancel={() => setDisconnectGithubOpen(false)} /> : null}
      </section>
      {workspace.role === "OWNER" ? <section className="py-6"><SectionHeading title="Zona de perigo" description="Ações permanentes para este workspace." destructive />
        {!deleteOpen ? <Button variant="outline" size="sm" className="mt-4 border-destructive/35 text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => setDeleteOpen(true)}><Trash />Excluir workspace</Button> : <form className="mt-4 grid gap-3 border-l-2 border-destructive bg-destructive/5 px-4 py-3" onSubmit={removeWorkspace}><label className="grid gap-1 text-sm">Digite {workspace.name} para confirmar<input className="h-9 rounded-md border border-input bg-background px-3" value={confirmName} onChange={e => setConfirmName(e.target.value)} /></label>{deleteError ? <p className="text-sm text-destructive">{deleteError}</p> : null}<div className="flex flex-wrap gap-2"><Button variant="destructive" size="sm" disabled={deleting || confirmName !== workspace.name}>Excluir definitivamente</Button><Button type="button" variant="ghost" size="sm" onClick={() => setDeleteOpen(false)}>Cancelar</Button></div></form>}
      </section> : null}
    </main>
  </section>;
}

function SectionHeading({ icon: Icon, title, description, destructive = false }: { icon?: typeof UsersThree; title: string; description: string; destructive?: boolean }) {
  return <div className="flex gap-3"><>{Icon ? <Icon className={`mt-0.5 h-5 w-5 ${destructive ? "text-destructive" : "text-primary"}`} /> : null}</><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div>;
}

function InlineConfirm({ title, description, confirmLabel, pending, onConfirm, onCancel }: { title: string; description: string; confirmLabel: string; pending: boolean; onConfirm: () => void; onCancel: () => void }) {
  return <div className="mt-4 grid gap-3 border-l-2 border-destructive bg-destructive/5 px-4 py-3"><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="destructive" disabled={pending} onClick={onConfirm}>{pending ? "Processando..." : confirmLabel}</Button><Button size="sm" variant="ghost" disabled={pending} onClick={onCancel}>Cancelar</Button></div></div>;
}
