import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { Replay, ReplayVersion } from "@/replays/replayApi";

export function ReplayVersionHistory({ replay, versions, loadVersion }: { replay: Replay; versions: ReplayVersion[]; loadVersion: (version: number) => Promise<ReplayVersion> }) {
  const [selected, setSelected] = useState<ReplayVersion | null>(null); const [loading, setLoading] = useState<number | null>(null);
  async function select(version: number) { setLoading(version); try { setSelected(await loadVersion(version)); } finally { setLoading(null); } }
  return <section className="border-t border-border pt-5"><p className="replay-section-label">Versões do conteúdo</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" size="sm" variant={selected ? "outline" : "secondary"} onClick={() => setSelected(null)}>v{replay.version} · Atual</Button>{versions.filter((value) => value.version !== replay.version).map((value) => <Button key={value.version} type="button" size="sm" variant={selected?.version === value.version ? "secondary" : "outline"} disabled={loading === value.version} onClick={() => void select(value.version)}>v{value.version}</Button>)}</div>{selected ? <article className="mt-4 grid gap-3 border-y border-border py-4"><p className="text-sm font-medium text-foreground">Versão histórica v{selected.version}</p><p className="text-sm text-muted-foreground">{selected.title}</p><p className="whitespace-pre-wrap text-sm text-muted-foreground">{selected.solution || selected.problem || selected.context || "Sem conteúdo adicional."}</p><p className="text-xs text-muted-foreground">Snapshot somente leitura · {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(selected.createdAt))}</p></article> : <p className="mt-3 text-sm text-muted-foreground">O estado atual é editável conforme sua permissão. Selecione uma versão para consultar seu snapshot somente leitura.</p>}</section>;
}
