import { useState } from "react";
import { LinkSimple, Trash } from "@phosphor-icons/react";
import { Button } from "@/components/ui/button";
import type { Replay, ReplayRelation, ReplayRelationType } from "@/replays/replayApi";

const labels: Record<ReplayRelationType, string> = { RELATED_TO: "Relacionado a", SUPERSEDES: "Substitui", RESOLVES: "Resolve", DEPENDS_ON: "Depende de" };

export function ReplayRelations({ relations, candidates, canWrite, onCreate, onDelete }: { relations: ReplayRelation[]; candidates: Replay[]; canWrite: boolean; onCreate: (targetReplayId: string, type: ReplayRelationType) => Promise<void>; onDelete: (relationId: string) => Promise<void> }) {
  const [target, setTarget] = useState(""); const [type, setType] = useState<ReplayRelationType>("RELATED_TO"); const [saving, setSaving] = useState(false);
  async function create() { if (!target) return; setSaving(true); try { await onCreate(target, type); setTarget(""); } finally { setSaving(false); } }
  return <section className="border-t border-border pt-4"><div className="flex items-center gap-2"><LinkSimple className="h-4 w-4 text-primary" /><p className="replay-section-label">Relações</p></div>{relations.length ? <ul className="mt-3 grid gap-2">{relations.map((relation) => <li key={relation.id} className="flex items-center justify-between gap-2 text-sm"><span className="min-w-0"><span className="font-medium text-foreground">{labels[relation.type]}</span><span className="mx-1 text-muted-foreground">→</span><span className="text-muted-foreground">{relation.relatedReplayTitle} · v{relation.relatedReplayVersion}</span></span>{canWrite ? <Button type="button" variant="ghost" size="icon" aria-label={`Remover relação com ${relation.relatedReplayTitle}`} onClick={() => void onDelete(relation.id)}><Trash className="h-4 w-4" /></Button> : null}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">Nenhuma relação registrada.</p>}{canWrite && candidates.length ? <div className="mt-3 grid gap-2"><select className="h-9 rounded-md border border-input bg-background px-2 text-sm" value={target} onChange={(event) => setTarget(event.target.value)}><option value="">Relacionar com…</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.title}</option>)}</select><div className="flex gap-2"><select className="h-9 min-w-0 flex-1 rounded-md border border-input bg-background px-2 text-sm" value={type} onChange={(event) => setType(event.target.value as ReplayRelationType)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button type="button" size="sm" disabled={!target || saving} onClick={() => void create()}>{saving ? "Salvando..." : "Adicionar"}</Button></div></div> : null}</section>;
}
