import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, ArrowsClockwise, GridFour, ListBullets, MagnifyingGlass, Plus } from "@phosphor-icons/react";
import { gsap } from "gsap";
import { Button } from "@/components/ui/button";
import type { Replay, ReplayStatus, ReplayType } from "@/replays/replayApi";

const typeLabels: Record<ReplayType, string> = { FIX: "Correção", PATTERN: "Padrão", RECIPE: "Receita", SNIPPET: "Snippet", DECISION: "Decisão", PROCEDURE: "Procedimento", CHECKLIST: "Checklist", TROUBLESHOOTING: "Troubleshooting", PROMPT: "Prompt", REFERENCE: "Referência" };
const statusLabels: Record<ReplayStatus, string> = { DRAFT: "Rascunho", VALIDATED: "Validado", DEPRECATED: "Descontinuado" };
type ExplorerId = "stack" | "type" | "problems" | "code";
type Selection = { label: string; matches: (replay: Replay) => boolean };
type CatalogView = "grid" | "list";
type CatalogSort = "RECENT" | "USED" | "UPDATED" | "TITLE";

export function ReplayCatalogHub({ items, metrics, filter, query, loading, error, search, canWrite, onQueryChange, onSearch, onFilterChange, onCreate, onOpen }: { items: Replay[]; metrics: { total: number; validated: number; usages: number }; filter: ReplayStatus | "ALL"; query: string; loading: boolean; error: string | null; search: boolean; canWrite: boolean; onQueryChange: (value: string) => void; onSearch: (value: string) => void; onFilterChange: (value: ReplayStatus | "ALL") => void; onCreate: () => void; onOpen: (item: Replay) => void }) {
  const hubRef = useRef<HTMLElement>(null);
  const [expanded, setExpanded] = useState<ExplorerId | null>(null);
  const [selection, setSelection] = useState<Selection | null>(null);
  const [view, setView] = useState<CatalogView>("grid");
  const [sort, setSort] = useState<CatalogSort>("RECENT");
  const [visibleCount, setVisibleCount] = useState(10);
  const stacks = useMemo(() => countValues(items.flatMap((replay) => replay.stack)), [items]);
  const replayTypes = useMemo(() => countValues(items.map((replay) => replay.type)), [items]);
  const tags = useMemo(() => countValues(items.flatMap((replay) => replay.tags)).slice(0, 6), [items]);
  const withProblem = useMemo(() => items.filter((replay) => Boolean(replay.problem?.trim())).length, [items]);
  const troubleshooting = useMemo(() => items.filter((replay) => replay.type === "TROUBLESHOOTING").length, [items]);
  const problemArtifacts = useMemo(() => items.filter((replay) => replay.type === "TROUBLESHOOTING" || Boolean(replay.problem?.trim()) || replay.tags.length > 0).length, [items]);
  const codeLanguages = useMemo(() => countValues(items.flatMap((replay) => codeBlocks(replay).map((block) => block.language))), [items]);
  const codeReplays = useMemo(() => items.filter((replay) => codeBlocks(replay).length > 0).length, [items]);
  const displayed = selection ? items.filter(selection.matches) : items;
  const sortedDisplayed = useMemo(() => [...displayed].sort((left, right) => {
    if (sort === "USED") return right.usageCount - left.usageCount || Date.parse(right.updatedAt) - Date.parse(left.updatedAt);
    if (sort === "UPDATED") return Date.parse(right.updatedAt) - Date.parse(left.updatedAt);
    if (sort === "TITLE") return left.title.localeCompare(right.title, "pt-BR");
    return Date.parse(right.lastUsedAt ?? right.updatedAt) - Date.parse(left.lastUsedAt ?? left.updatedAt);
  }), [displayed, sort]);
  const visibleDisplayed = sortedDisplayed.slice(0, visibleCount);

  function choose(next: Selection) { setSelection(next); setExpanded(null); setVisibleCount(10); }
  function toggle(id: ExplorerId) { setExpanded((current) => current === id ? null : id); }

  useEffect(() => { setVisibleCount(10); }, [filter, query, selection?.label, sort, view]);

  useLayoutEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches || !hubRef.current) return;
    const context = gsap.context(() => {
      gsap.from("[data-replay-enter]", { autoAlpha: 0, y: 16, duration: .42, stagger: .07, ease: "power3.out", clearProps: "transform" });
    }, hubRef);
    return () => context.revert();
  }, []);

  useLayoutEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches || !hubRef.current) return;
    const context = gsap.context(() => { gsap.fromTo("[data-replay-catalog-item]", { autoAlpha: 0, y: 10 }, { autoAlpha: 1, y: 0, duration: .28, stagger: .035, ease: "power3.out", clearProps: "transform" }); }, hubRef);
    return () => context.revert();
  }, [sort, view, selection?.label, visibleDisplayed.length]);

  return <section ref={hubRef} className="replay-hub">
    <header className="replay-hub__header" data-replay-enter>
      <div className="replay-hub__lead"><p className="replay-section-label">Conhecimento / Replays / Hub técnico</p><h2>Reuso técnico, em contexto.</h2><p>Explore soluções, decisões e evidências sem perder a trilha do trabalho.</p></div>
      <div className="replay-hub__aside"><div className="replay-hub__metrics" aria-label="Resumo do catálogo"><span><strong>{metrics.total}</strong> Replays</span><span><strong>{metrics.validated}</strong> validados</span><span><strong>{metrics.usages}</strong> usos</span></div>{canWrite ? <Button onClick={onCreate}><Plus className="h-4 w-4" />Novo Replay</Button> : null}</div>
    </header>

    <section className="replay-hub__controls" aria-label="Localizar conhecimento" data-replay-enter>
      <form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); onSearch(query.trim()); }}><label className="relative min-w-0 flex-1"><MagnifyingGlass className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-primary" /><span className="sr-only">Buscar Replays</span><input className="h-12 w-full border-0 bg-transparent py-2 pl-10 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Buscar problema, solução, stack..." /></label><Button type="submit" variant="ghost" size="icon" aria-label="Buscar"><MagnifyingGlass className="h-4 w-4" /></Button></form>
      <div className="replay-filters" aria-label="Filtrar Replays">{(["ALL", "VALIDATED", "DRAFT", "DEPRECATED"] as const).map((value) => <Button key={value} type="button" size="sm" variant={filter === value ? "default" : "ghost"} className={filter === value ? "replay-filter replay-filter--active" : "replay-filter"} onClick={() => onFilterChange(value)}>{value === "ALL" ? "Todos" : statusLabels[value]}</Button>)}</div>
    </section>

    {!loading && items.length ? <section className="replay-explorer" aria-labelledby="replay-explorer-title" data-replay-enter><div className="replay-hub__section-heading"><div><p className="replay-section-label">Descoberta</p><h3 id="replay-explorer-title">Explorar</h3></div><span>{items.length} artefatos no recorte</span></div><div className="replay-explorer__grid">
      <ExplorerSection id="stack" label="Stack" description="Tecnologias presentes nos Replays." count={stacks.reduce((total, group) => total + group.count, 0)} expanded={expanded === "stack"} onToggle={toggle}>{stacks.length ? stacks.map((group) => <ExplorerChoice key={group.value} active={selection?.label === group.value} label={group.value} count={group.count} onClick={() => choose({ label: group.value, matches: (replay) => replay.stack.includes(group.value) })} />) : <ExplorerEmpty>Sem stacks registradas no recorte.</ExplorerEmpty>}</ExplorerSection>
      <ExplorerSection id="type" label="Tipo" description="Forma técnica de cada artefato." count={replayTypes.reduce((total, group) => total + group.count, 0)} expanded={expanded === "type"} onToggle={toggle}>{replayTypes.map((group) => <ExplorerChoice key={group.value} active={selection?.label === typeLabels[group.value as ReplayType]} label={typeLabels[group.value as ReplayType]} count={group.count} onClick={() => choose({ label: typeLabels[group.value as ReplayType], matches: (replay) => replay.type === group.value })} />)}</ExplorerSection>
      <ExplorerSection id="problems" label="Problemas" description="Sinais extraídos de problemas e tags." count={problemArtifacts} expanded={expanded === "problems"} onToggle={toggle}>{troubleshooting ? <ExplorerChoice active={selection?.label === "Troubleshooting"} label="Troubleshooting" count={troubleshooting} onClick={() => choose({ label: "Troubleshooting", matches: (replay) => replay.type === "TROUBLESHOOTING" })} /> : null}{withProblem ? <ExplorerChoice active={selection?.label === "Com problema registrado"} label="Com problema registrado" count={withProblem} onClick={() => choose({ label: "Com problema registrado", matches: (replay) => Boolean(replay.problem?.trim()) })} /> : null}{tags.map((group) => <ExplorerChoice key={group.value} active={selection?.label === `#${group.value}`} label={`#${group.value}`} count={group.count} onClick={() => choose({ label: `#${group.value}`, matches: (replay) => replay.tags.includes(group.value) })} />)}{!troubleshooting && !withProblem && !tags.length ? <ExplorerEmpty>Sem sinais de problema registrados no recorte.</ExplorerEmpty> : null}</ExplorerSection>
      <ExplorerSection id="code" label="Código reutilizável" description="Linguagens extraídas de blocos fenced." count={codeReplays} expanded={expanded === "code"} onToggle={toggle}>{codeLanguages.length ? codeLanguages.map((group) => <ExplorerChoice key={group.value} active={selection?.label === group.value} label={group.value} count={group.count} onClick={() => choose({ label: group.value, matches: (replay) => codeBlocks(replay).some((block) => block.language === group.value) })} />) : <ExplorerEmpty>Nenhum bloco fenced no recorte.</ExplorerEmpty>}</ExplorerSection>
    </div></section> : null}

    {error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}
    {loading ? <p className="replay-hub__loading text-sm text-muted-foreground">Carregando Replays...</p> : displayed.length === 0 ? <HubEmptyState search={search} selection={Boolean(selection)} canWrite={canWrite} onCreate={onCreate} onClearSearch={() => { onQueryChange(""); onSearch(""); }} onClearSelection={() => { setSelection(null); setVisibleCount(10); }} /> : <section className="replay-hub__catalog" aria-labelledby="replay-hub-catalog" data-replay-enter><div className="replay-hub__catalog-header"><div><p className="replay-section-label">Catálogo técnico</p><h3 id="replay-hub-catalog">{selection ? selection.label : filter === "ALL" ? "Todos os artefatos" : statusLabels[filter]}</h3></div><div className="replay-hub__catalog-controls"><div className="replay-hub__view-toggle" aria-label="Visualização do catálogo"><Button type="button" variant={view === "grid" ? "default" : "ghost"} size="sm" aria-pressed={view === "grid"} onClick={() => setView("grid")}><GridFour className="h-4 w-4" />Grade</Button><Button type="button" variant={view === "list" ? "default" : "ghost"} size="sm" aria-pressed={view === "list"} onClick={() => setView("list")}><ListBullets className="h-4 w-4" />Lista</Button></div><label className="replay-hub__sort"><span>Ordenar</span><select value={sort} onChange={(event) => setSort(event.target.value as CatalogSort)}><option value="RECENT">Mais recentes</option><option value="USED">Mais usados</option><option value="UPDATED">Atualizados</option><option value="TITLE">A–Z</option></select></label></div></div><div className="replay-list__caption"><span>{sortedDisplayed.length} resultado{sortedDisplayed.length === 1 ? "" : "s"}</span>{selection ? <span className="replay-hub__active-filter">Filtro: {selection.label}<button type="button" aria-label={`Limpar filtro ${selection.label}`} onClick={() => { setSelection(null); setVisibleCount(10); }}>×</button></span> : null}</div><div className={view === "grid" ? "replay-catalog-grid" : "replay-list replay-list--compact"}>{visibleDisplayed.map((item, index) => view === "grid" ? <CatalogGridItem key={item.id} item={item} index={index + 1} onOpen={() => onOpen(item)} /> : <CatalogItem key={item.id} item={item} index={index + 1} onOpen={() => onOpen(item)} />)}</div>{visibleDisplayed.length < sortedDisplayed.length ? <button type="button" className="replay-hub__show-more" onClick={() => setVisibleCount((current) => Math.min(current + 10, sortedDisplayed.length))}>Exibir mais <span>{visibleDisplayed.length}/{sortedDisplayed.length}</span></button> : null}</section>}
  </section>;
}

function ExplorerSection({ id, label, description, count, expanded, onToggle, children }: { id: ExplorerId; label: string; description: string; count: number; expanded: boolean; onToggle: (id: ExplorerId) => void; children: React.ReactNode }) { const sectionRef = useRef<HTMLElement>(null); useLayoutEffect(() => { if (!expanded || window.matchMedia("(prefers-reduced-motion: reduce)").matches || !sectionRef.current) return; const context = gsap.context(() => { const panel = sectionRef.current?.querySelector(".replay-explorer__panel"); const rail = sectionRef.current?.querySelector(".replay-explorer__rail"); if (!panel || !rail) return; const timeline = gsap.timeline({ defaults: { ease: "power3.out" } }); timeline.fromTo(rail, { scaleY: .15 }, { scaleY: 1, duration: .28, transformOrigin: "top" }).from(panel, { clipPath: "inset(0 0 100% 0)", duration: .28 }, "<.04").from(panel.querySelectorAll("button, p"), { autoAlpha: 0, x: -10, duration: .2, stagger: .04 }, "<.08"); }, sectionRef); return () => context.revert(); }, [expanded]); return <section ref={sectionRef} className={expanded ? "replay-explorer__section replay-explorer__section--expanded" : "replay-explorer__section"}><span className="replay-explorer__rail" aria-hidden="true" /><button type="button" className="replay-explorer__trigger" aria-expanded={expanded} aria-controls={`replay-explorer-${id}`} onClick={() => onToggle(id)}><span><span className="replay-section-label">{String(["stack", "type", "problems", "code"].indexOf(id) + 1).padStart(2, "0")}</span><strong>{label}</strong><small>{description}</small></span><span><b>{count}</b><em>{expanded ? "Fechar" : "Explorar"}</em><ArrowRight className="h-4 w-4" /></span></button>{expanded ? <div id={`replay-explorer-${id}`} className="replay-explorer__panel">{children}</div> : null}</section>; }
function ExplorerChoice({ label, count, active, onClick }: { label: string; count: number; active: boolean; onClick: () => void }) { return <button type="button" className={active ? "replay-explorer__choice replay-explorer__choice--active" : "replay-explorer__choice"} onClick={onClick}><span>{label}</span><b>{count}</b></button>; }
function ExplorerEmpty({ children }: { children: React.ReactNode }) { return <p className="replay-explorer__empty">{children}</p>; }
function HubEmptyState({ search, selection, canWrite, onCreate, onClearSearch, onClearSelection }: { search: boolean; selection: boolean; canWrite: boolean; onCreate: () => void; onClearSearch: () => void; onClearSelection: () => void }) { const hasNoResults = search || selection; return <div className="replay-hub__empty"><p className="font-medium text-foreground">{hasNoResults ? "Nenhum Replay encontrado." : "Este workspace ainda não possui Replays."}</p><p>{hasNoResults ? "Tente outro termo, ajuste o filtro ou limpe a exploração atual." : "Registre soluções, padrões e contexto técnico que podem ser reutilizados."}</p>{search ? <Button variant="outline" size="sm" onClick={onClearSearch}>Limpar busca</Button> : selection ? <Button variant="outline" size="sm" onClick={onClearSelection}>Limpar exploração</Button> : canWrite ? <Button size="sm" onClick={onCreate}>Criar primeiro Replay</Button> : null}</div>; }
function CatalogItem({ item, index, onOpen }: { item: Replay; index: number; onOpen: () => void }) { const summary = plainExcerpt(item.problem) || plainExcerpt(item.solution) || "Sem resumo técnico registrado."; return <button type="button" data-replay-catalog-item className="replay-list-item replay-list-item--compact group" onClick={onOpen}><span className="replay-list-item__index" aria-hidden="true">{String(index).padStart(2, "0")}</span><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><span className="min-w-0 truncate font-semibold text-foreground group-hover:text-primary">{item.title}</span><span className="replay-type-mark">{typeLabels[item.type]}</span></span><span className="mt-1 block line-clamp-2 text-sm leading-5 text-muted-foreground">{summary}</span><span className="replay-list-item__meta"><span>{item.stack[0] ?? "Sem stack"}</span><span>v{item.version}</span><span><ArrowsClockwise className="h-3 w-3" />{item.usageCount} usos</span><span>Atualizado {formatDate(item.updatedAt)}</span></span></span><span className="replay-list-item__signals"><span className={`replay-status replay-status--${item.status.toLowerCase()}`}>{statusLabels[item.status]}</span></span></button>; }
function CatalogGridItem({ item, index, onOpen }: { item: Replay; index: number; onOpen: () => void }) { const summary = plainExcerpt(item.problem) || plainExcerpt(item.solution) || "Sem resumo técnico registrado."; return <button type="button" data-replay-catalog-item className="replay-catalog-grid__item group" onClick={onOpen}><span className="replay-catalog-grid__rail" aria-hidden="true" /><span className="replay-catalog-grid__index" aria-hidden="true">{String(index).padStart(2, "0")}</span><span className="replay-catalog-grid__signals"><span className="replay-type-mark">{typeLabels[item.type]}</span><span className={`replay-status replay-status--${item.status.toLowerCase()}`}>{statusLabels[item.status]}</span></span><span className="replay-catalog-grid__title">{item.title}</span><span className="replay-catalog-grid__summary">{summary}</span><span className="replay-catalog-grid__metadata"><span>{item.stack.length ? item.stack.join(" / ") : "Sem stack"}</span><span>v{item.version}</span><span><ArrowsClockwise className="h-3 w-3" />{item.usageCount} usos</span><span>Atualizado {formatDate(item.updatedAt)}</span></span>{item.tags.length ? <span className="replay-catalog-grid__tags">{item.tags.slice(0, 4).map((tag) => <span key={tag} className="replay-tag">{tag}</span>)}</span> : null}</button>; }
function countValues(values: string[]) { return Array.from(values.reduce((counts, value) => counts.set(value, (counts.get(value) ?? 0) + 1), new Map<string, number>()).entries()).map(([value, count]) => ({ value, count })).sort((left, right) => right.count - left.count || left.value.localeCompare(right.value, "pt-BR")); }
function codeBlocks(replay: Replay) { return [replay.problem, replay.context, replay.solution].flatMap((content) => Array.from((content ?? "").matchAll(/```([^\n`]*)\r?\n([\s\S]*?)```/g), (match) => ({ language: match[1].trim() || "texto" }))); }
function plainExcerpt(value: string | null) { return (value ?? "").replace(/```[\s\S]*?```/g, " ").replace(/[#>*_[\]()`-]/g, " ").replace(/\s+/g, " ").trim(); }
function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)); }
